### PR TITLE
adapt to v0.52

### PR DESCRIPTION
**Pull request by arnehilmann**
please check the generated pdf first!
then try rebuilding it by removing the whole deck folder first...
known problem: arrows of operator slide disappear on first load (you have to reload it) and when you advance more than 3 slides...

### CODE REVIEW

**Comment by gerald1248** [comment]
Looking great, thank you! Will check outputs asap.

**Comment by gerald1248** [comment]
This is a lot closer! The remaining issues I see are:

* the built-in shapes (cloud, storage) for a2sketch/a2s don't work
* the repo's README.md is picked up as first slide (this may be a feature in the sense of parsing all *.md in the root folder?)
* some arrow tip weirdness (presumably ID collisions as you suggest)
* PDF not rendered

**Comment by arnehilmann** [comment]
No pdf rendered? 😳
Did the pdf renderer log anything? 
did you touch/modify the slides file? 
Did you remove/rename the readme file?
(BTW: The PDF rendering takes more than 40secs...)

**Comment by arnehilmann** [comment]
Please try again:  pdf and custom/builtin a2s shapes should be working now.
Work on the arrow issue is still pending...

**Comment by gerald1248** [comment]
Thank you so much! Have merged & will find another route around the arrows issue.

**Comment by arnehilmann** [comment]
regarding the  arrows issue: please give PR#2 a try, too...

**Pull request merged**
